#Configuration file for the subdomains used in the training and validation phase
!!python/tuple
- !!python/tuple
  - training
  - lat_min: 30.
    lat_max: 55.
    lon_min: -50.
    lon_max: -20.
- !!python/tuple
  - training
  - lat_min: -45.
    lat_max: -10.
    lon_min: -185.
    lon_max: -150.
- !!python/tuple
  - training
  - lat_min: -30.
    lat_max: 5.
    lon_min: -120.
    lon_max: -80.
- !!python/tuple
  - training
  - lat_min: -20.
    lat_max: 20.
    lon_min: -180
    lon_max: -150
