#Configuration file for the subdomains used in the training and validation phase
!!python/tuple
- !!python/tuple
  - training
  - lat_min: 30.
    lat_max: 55.
    lon_min: -50.
    lon_max: -20.
- !!python/tuple
  - training
  - lat_min: -45.
    lat_max: -20.
    lon_min: -175.
    lon_max: -157.
- !!python/tuple
  - training
  - lat_min: -30.
    lat_max: 5.
    lon_min: -120.
    lon_max: -80.
- !!python/tuple
  - training
  - lat_min: 0.
    lat_max: 25.
    lon_min: -48.
    lon_max: -20.
